#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Completions, may need to run `autoload -Uz compinit && compinit -i` if new completions are added and not showing up.
# `rm -r .zcompdump` if rvm errors show after that.
fpath=(/usr/local/share/zsh/site-functions $fpath)


# Add ssh passphrases to keychain
ssh-add -A &> /dev/null


# RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


# NVM
export NVM_DIR="/Users/Russell/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm


# GOLANG
export GOPATH=$HOME/Developer/Go
export PATH=$PATH:$GOPATH/bin
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOROOT/bin


# GCP
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/Russell/Developer/Tools/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/Russell/Developer/Tools/google-cloud-sdk/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/Users/Russell/Developer/Tools/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/Russell/Developer/Tools/google-cloud-sdk/completion.zsh.inc'; fi


# AWS
export PATH=$PATH:/Users/Russell/Library/Python/3.6/bin
source /Users/Russell/Library/Python/3.6/bin/aws_zsh_completer.sh

# Flutter
export PATH="$PATH":/Users/Russell/Developer/Tools/flutter/bin

# Aliases
alias dockerrm='docker rm -v $(docker ps -a -q)'
alias dockerrmi='docker rmi $(docker images -q)'
alias dockerrmid='docker rmi $(docker images -q -f "dangling=true")'
alias la='ls -laO'
